import { Component } from '@angular/core';

@Component({
  selector: 'app-wallet-transfers',
  templateUrl: './wallet-transfers.component.html',
  styleUrls: ['./wallet-transfers.component.sass'],
})
export class WalletTransfersComponent {
  tableData = [
    // {
    //   date: '2023-09-08',
    //   sendAmount: 'GDP100',
    //   customerRef: 'UKSP3450',
    //   receivingCurrency: 'INR 8915',
    //   paymentMode: 'Bank Transfer',
    //   transferMode: 'Bank Deposit',
    //   totalPayable: 'GBP 102',
    //   senderName: 'Mark Antony',
    //   agentName: 'qa_Spoton Money',
    //   telephone: '0112232248',
    //   beneficiaryName: 'Faiz Muradh',
    //   status: '3rd SEP',
    //   ip: '111.223.191.136',
    //   benificiryCountry:'USA',
    //    payingBy:'ABCXC',
    // },
    // {
    //   date: '2023-09-08',
    //   sendAmount: 'GDP100',
    //   customerRef: 'UKSP3450',
    //   receivingCurrency: 'INR 8915',
    //   paymentMode: 'Bank Transfer',
    //   transferMode: 'Bank Deposit',
    //   totalPayable: 'GBP 102',
    //   senderName: 'Mark Antony',
    //   agentName: 'qa_Spoton Money',
    //   telephone: '0112232248',
    //   beneficiaryName: 'Faiz Muradh',
    //   status: '3rd SEP',
    //   ip: '111.223.191.136',
    //   benificiryCountry:'USA',
    //    payingBy:'ABCXC'
    // },
    // {
    //   date: '2023-09-08',
    //   sendAmount: 'GDP100',
    //   customerRef: 'UKSP3450',
    //   receivingCurrency: 'INR 8915',
    //   paymentMode: 'Bank Transfer',
    //   transferMode: 'Bank Deposit',
    //   totalPayable: 'GBP 102',
    //   senderName: 'Mark Antony',
    //   agentName: 'qa_Spoton Money',
    //   telephone: '0112232248',
    //   beneficiaryName: 'Faiz Muradh',
    //   status: '3rd SEP',
    //   ip: '111.223.191.136',
    //   benificiryCountry:'USA',
    //    payingBy:'ABCXC'
    // },
    // {
    //   date: '2023-09-08',
    //   sendAmount: 'GDP100',
    //   customerRef: 'UKSP3450',
    //   receivingCurrency: 'INR 8915',
    //   paymentMode: 'Bank Transfer',
    //   transferMode: 'Bank Deposit',
    //   totalPayable: 'GBP 102',
    //   senderName: 'Mark Antony',
    //   agentName: 'qa_Spoton Money',
    //   telephone: '0112232248',
    //   beneficiaryName: 'Faiz Muradh',
    //   status: '3rd SEP',
    //   ip: '111.223.191.136',
    //   benificiryCountry:'USA',
    //    payingBy:'ABCXC'
    // },
    // {
    //   date: '2023-09-08',
    //   sendAmount: 'GDP100',
    //   customerRef: 'UKSP3450',
    //   receivingCurrency: 'INR 8915',
    //   paymentMode: 'Bank Transfer',
    //   transferMode: 'Bank Deposit',
    //   totalPayable: 'GBP 102',
    //   senderName: 'Mark Antony',
    //   agentName: 'qa_Spoton Money',
    //   telephone: '0112232248',
    //   beneficiaryName: 'Faiz Muradh',
    //   status: '3rd SEP',
    //   ip: '111.223.191.136',
    //   benificiryCountry:'USA',
    //   payingBy:'ABCXC'
    // },
  ];
}
